key_mapping_front = {
    "market_capitalization": "Капитализация",
    "ticker": "Тикер",
    # "currency": "Валюта",
    # "high_price_last_52_weeks": "Макс. цена за 52 недели",
    # "low_price_last_52_weeks": "Мин. цена за 52 недели",
    # "average_daily_volume_last_10_days": "Ср. объём за 10 дней",
    # "average_daily_volume_last_4_weeks": "Ср. объём за 4 недели",
    # "beta": "Бета",
    # "free_float": "Флоат",
    "forward_annual_dividend_yield": "Дивидендная доходность, прогноз",
    "shares_outstanding": "Количество акций",
    "revenue_ttm": "Выручка",
    "ebitda_ttm": "EBITDA",
    "net_income_ttm": "Чистая прибыль",
    "eps_ttm": "EPS",
    "pe_ratio_ttm": "P/E",
    "price_to_sales_ttm": "P/S",
    "price_to_book_ttm": "P/BV",
    # "total_enterprise_value_mrq": "Стоимость компании (MRQ)",
    "ev_to_ebitda_mrq": "EV/EBITDA",
    "ev": "EV",  # <-
    "roe": "ROE",
    "roa": "ROA",
    # "roic": "ROIC",
    # "total_debt_to_equity_mrq": "Debt/Equity (MRQ)",
    "total_debt_to_ebitda_mrq": "Долг/EBITDA",
    # "dividend_yield_daily_ttm": "Дивидендная доходность (TTM)",
    # "current_ratio_mrq": "Текущий коэффициент (MRQ)",
    "dividend_rate_ttm": "Див доход, ао",
    "dividends_per_share": "Дивиденд",
    # "five_years_average_dividend_yield": "Ср. див. доходность за 5 лет",
    "dividend_payout_ratio_fy": "Дивиденды/прибыль",
    # "buy_back_ttm": "Обратный выкуп (TTM)",
    # "one_year_annual_revenue_growth_rate": "Годовой рост выручки (1 год)",
    # "revenue_change_five_years": "Изменение выручки за 5 лет",
    # "eps_change_five_years": "Изменение EPS за 5 лет",
    # "ev_to_sales": "EV/Выручка",
    # "ex_dividend_date": "Дата ex-dividend",
}

multip = [
    "market_capitalization",
    "ticker",
    "currency",
    "high_price_last_52_weeks",
    "low_price_last_52_weeks",
    "average_daily_volume_last_10_days",
    "average_daily_volume_last_4_weeks",
    "beta",
    "free_float",
    "forward_annual_dividend_yield",
    "shares_outstanding",
    "revenue_ttm",
    "ebitda_ttm",
    "net_income_ttm",
    "eps_ttm",
    "pe_ratio_ttm",
    "price_to_sales_ttm",
    "price_to_book_ttm",
    "total_enterprise_value_mrq",
    "ev_to_ebitda_mrq",
    "roe",
    "roa",
    "roic",
    "total_debt_to_equity_mrq",
    "total_debt_to_ebitda_mrq",
    "dividend_yield_daily_ttm",
    "current_ratio_mrq",
    "dividend_rate_ttm",
    "dividends_per_share",
    "five_years_average_dividend_yield",
    "dividend_payout_ratio_fy",
    "buy_back_ttm",
    "one_year_annual_revenue_growth_rate",
    "revenue_change_five_years",
    "eps_change_five_years",
    "ev_to_sales",
    "ex_dividend_date",
]
